from app.models.author import Author
from app.models.author_merge_log import AuthorMergeLog
from app.models.author_topic import AuthorTopic
from app.models.author_work import AuthorWork
from app.models.author_work_afiliation import AuthorWorkAffiliation
from app.models.author_yearly_metric import AuthorYearlyMetric
from app.models.institution import Institution
from app.models.prisma_author import PrismaAuthor
from app.models.research_group import ResearchGroup
from app.models.source import Source
from app.models.topic import Topic
from app.models.user import User
from app.models.user_log import UserLog
from app.models.work import Work
from app.models.work_reference import WorkReference
from app.models.work_topic import WorkTopic
