# services:
#   # --------------------------------------------------------
#   # 1. SERVICIO DE BASE DE DATOS (PostgreSQL)
#   # --------------------------------------------------------
#   db:
#     image: postgres:17 # Descarga la versión oficial 15 de PostgreSQL
#     container_name: sinergia_db
#     restart: always     # Si falla o reinicias el PC, se vuelve a encender solo
#     environment:
#       # Credenciales de tu BBDD (las mismas que pusimos en database.py)
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: password123
#       POSTGRES_DB: sinergia_db
#     ports:
#       - "5432:5432"     # Mapea el puerto de tu PC al puerto del contenedor
#     volumes:
#       # 1. Automagia: Ejecuta tu script SQL al crear la BBDD por primera vez
#       - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
#       # 2. Persistencia: Guarda los datos en tu disco duro para no perderlos
#       - postgres_data:/var/lib/postgresql/data

services:
  db:
    image: postgres:18
    container_name: postgresql_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sinergia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:

#   # --------------------------------------------------------
#   # 2. SERVICIO DE BACKEND (Tu API con FastAPI)
#   # --------------------------------------------------------
#   backend:
#     build: .            # Busca un archivo llamado 'Dockerfile' en esta misma carpeta
#     container_name: sinergia_api
#     restart: always
#     ports:
#       - "8000:8000"     # Tu API estará disponible en localhost:8000
#     environment:
#       # Le pasamos la cadena de conexión para que tu código Python la lea
#       - DATABASE_URL=postgresql://admin:password123@db:5432/sinergia_db
#     depends_on:
#       - db              # Le dice a Docker: "No arranques FastAPI hasta que la BBDD esté lista"
#     volumes:
#       # Sincroniza tu código local con el contenedor (si cambias algo en Python, se actualiza solo)
#       - .:/app

# # --------------------------------------------------------
# # VOLÚMENES GLOBALES
# # --------------------------------------------------------
# volumes:
#   postgres_data: # Define el volumen físico para guardar los datos de OpenAlex