"""apply_db_diagram

Revision ID: d16942e267fa
Revises: 1e96983ff295
Create Date: 2026-08-10 19:56:04.365827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16942e267fa'
down_revision: Union[str, Sequence[str], None] = '1e96983ff295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'author_work_affiliations', 'authors', ['author_id'], ['id'])
    op.create_foreign_key(None, 'author_work_affiliations', 'works', ['work_id'], ['id'])
    op.alter_column('institutions', 'works_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('institutions', 'cited_by_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('institutions', 'cited_by_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('institutions', 'works_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'author_work_affiliations', type_='foreignkey')
    op.drop_constraint(None, 'author_work_affiliations', type_='foreignkey')
    # ### end Alembic commands ###
